### ISSUE TITLE
Can we add remove method to this library?

### ISSUE THREAD

**Issue by iinsta** [lukeed/trouter#3] opened 2018-02-03 18:57 UTC

**Comment by lukeed** [comment] 2018-02-03 19:05
Hey, what do you mean? There's already a `app.delete` method attached. Trouter automatically attaches _all_ `http.METHODS` to itself.

You can see the test output here: https://travis-ci.org/lukeed/trouter/jobs/327613582#L609

**Comment by iinsta** [comment] 2018-02-03 20:13
I mean add a `remove` method  like unsubscribe to subscribe: 

```js
	add(method, pattern, handler) {
		// Save decoded pattern info
		this.routes[method].push(parse(pattern));
		// Save route handler
		this.handlers[method][pattern] = handler;
		// Allow chainable
		return this;
	}
    remove(method, pattern, handler) {
      // remove add method
   }
```
https://github.com/lukeed/trouter/blob/master/lib/index.js#L16-L23

**Comment by lukeed** [comment] 2018-02-03 20:15
Ah, gotcha. May I ask the purpose/reason for doing this?

**Comment by iinsta** [comment] 2018-02-03 20:20
Then we can have config to generate and disable router in fly, not restart

**Comment by lukeed** [comment] 2018-02-03 20:25
You can't have a dynamic route handler? Sorry, I've never seen this need before

**Comment by iinsta** [comment] 2018-02-03 20:37
Dynamic route can't process this kind:

```js
app.use('/web1/images', serve('./web1/assets/images'))
app.use('/web2/images', serve('./web2/assets/images')) 
// I know how to add `'/web3/images'`
// but how to disable `'/web2/images'` on fly?
```

**Comment by lukeed** [comment] 2018-09-17 16:51
Closing this as I still see no need for this in a Node.js server context. 

I'm open to being convinced otherwise, but haven't been yet 😉Can reopen for discussion at that time.

Thanks!

**Closed by lukeed** 2018-09-17 16:51 UTC

**Comment by bugs181** [comment] 2018-12-06 23:56
Sorry, I have to disagree. Just because YOU don't see a need only hints at lack of imagination. I was actually coming here with the intention of replacing my custom router scenario on a much bigger project, needing this functionality. My use case is extremely simple, private (recursive/) routing capabilities.

1. Project loads all routes from a config (just as posted)
2. Config is processed into a router to do transformations
3. Some of those routes (via transformations) may need to be "private" so they go into a private router instance.
4. Router (trouter) would be send to protocols to be served up to the public.

That in mind, I'd need `.delete` or `.remove` (don't really have a preference) and a `.forEach` method to accomplish my goals.

**Comment by lukeed** [comment] 2018-12-07 00:33
@bugs181 Sounds like you need two routers.


```js
const privRouter = new Trouter();
const publRouter = new Trouter();

myRoutes.forEach(obj => {
  let router = obj.isPrivate ? privRouter : publRouter;
  router.add(obj.method, obj.pattern, ...obj.handlers);
});
```

**Comment by bugs181** [comment] 2018-12-08 17:20
The problem is that I would have to have knowledge up front about which routes to put in what router. This is impossible with my scenario as `transformer` plugins can mark routes as being private. That would mean, I would have to duplicate `trouter` work - just to provide this functionality, that could be solved with a simple `.remove` function.

**Comment by lukeed** [comment] 2018-12-08 17:52
Well, Trouter is a class. You can import it and add your own method to the prototype.

Or not use Trouter at all and roll your own like I did.

This won't be added to Trouter, NOT because I lack imagination (rude, thanks) but because I'm purposefully discouraging poor server design. Popping off routes will deoptimize the runtime of your server. It may not matter with low-traffic side projects, but it certainly matters with high traffic/stress.

You have options.

**Comment by bugs181** [comment] 2018-12-09 01:56
I never said the server started before the router was able to process the routes. I apologize that you think my constructive criticism is rude. I've seen so many projects/libraries fail because authors, much like yourself think they know all use-cases. Please do take this as constructive feedback. 

You also making the assumption that this is somehow "poor server design" - because you don't understand the project stack I'm dealing with - could also be construed as rude and insulting. 

The idea is to have multiple `trouter` instances with a coordination mechanism about where to apply what routes (that can't be known until transformation runtimes happen). In addition to that, the project I'm working on is much like how Babel works - you can compile your routes (and transformations) for optimizations. Nothing about this is "poor design" - unless you are saying that the thousands of other libs that have any sort of pre-compilation or post-compilation hooks (such as that of babel) are designed poorly.

**Comment by lukeed** [comment] 2018-12-09 01:57
I understand fully. This is the implementation I've chosen to share publicly and maintain. You don't have to use it.

Good luck with your project
